name: YouTube Radio Stream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # يعيد التشغيل كل 6 ساعات

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install ffmpeg -y

    - name: Run Stream
      env:
        RADIO_URL: ${{ secrets.RADIO_URL }}
        YOUTUBE_URL: ${{ secrets.YOUTUBE_URL }}
      run: bash radio.sh
